### PR TITLE
Changing select boxes to text on required members.  Adding in role in…

### PR DESCRIPTION
**Pull request by cam156**
… email and name labels. refs #95

Original Screen
screen shot 2016-04-07 at 2 27 00 pm

Screen after PR
screen shot 2016-04-07 at 2 25 41 pm

### CODE REVIEW

**Comment by cam156** [comment]
@jonibar Do you think this is better?  The apple voice over now reads the labels.

**Comment by jonibar** [comment]
@cam156 - Yes that'll work.  If you'd prefer to have all boxes look the same with name, email as labels, <span class='sr-only'>Committee Member <span>name can be used.  The screen reader will read the same label either way.  It's up to you.  Thanks!

**Comment by cam156** [comment]
Changed the role to be a heading and added a SR header for the optional items.

screen shot 2016-04-08 at 10 28 35 am

@jonibar  This should be good to go once it is green

**Comment by cam156** [comment]
@jonibar is we want to go back to just Name and Email we can.  The screen reader is now reading the heading well.  I can make that Update so it will look visually closer to the original.

**Pull request merged**
